name: Deploy to NuGet

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  PROJECT_PATH: Ultimaker.ApiClient.Core/Ultimaker.ApiClient.Core.csproj
  PACKAGE_OUTPUT_DIR: ${{ github.workspace }}/output

jobs:
  release:
    name: Release to NuGet
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v5
        with:
          branch: main
          dry_run: true
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/changelog
            @semantic-release/git
            @semantic-release/github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Pack
        run: dotnet pack $PROJECT_PATH --configuration Release --no-build -o $PACKAGE_OUTPUT_DIR
      - name: Push to NuGet
        run: dotnet nuget push "$PACKAGE_OUTPUT_DIR/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
